<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net461</TargetFrameworks>
    <PackOnBuild>true</PackOnBuild>
    <Authors>antopen</Authors>
    <NeutralLanguage>zh</NeutralLanguage>
    <PackageLicenseUrl>https://github.com/alipay/alipay-easysdk/blob/master/LICENSE</PackageLicenseUrl>
    <Description></Description>
    <PackageId>NjxyMall.AlipayEasySDK</PackageId>
    <Owners>antopen</Owners>
    <PackageProjectUrl>https://github.com/renshiyou/alipay-easysdk</PackageProjectUrl>
    <Summary>Alipay Easy SDK for .NET allows you to enjoy a minimalist programming experience and quickly access the various high-frequency capabilities of the Alipay Open Platform.</Summary>
    <Title>Alipay Easy SDK</Title>
    <Version>0.0.2</Version>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType></DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Factory\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AlipayEasySDK.Kernel" Version="1.0.6" />
  </ItemGroup>
</Project>
